package export

// Generated by 'go run gen.go crypto/rand'. Do not edit!

import "crypto/rand"

var sym_rand = &map[string]interface{}{
	"Int":    rand.Int,
	"Prime":  rand.Prime,
	"Read":   rand.Read,
	"Reader": rand.Reader,
}
