package export

// Generated by 'goexports net/mail'. Do not edit!

import "net/mail"

// NetMail contains exported symbols from net/mail
var NetMail = &map[string]interface{}{
	"Address":             new(mail.Address),
	"AddressParser":       new(mail.AddressParser),
	"ErrHeaderNotPresent": mail.ErrHeaderNotPresent,
	"Header":              new(mail.Header),
	"Message":             new(mail.Message),
	"ParseAddress":        mail.ParseAddress,
	"ParseAddressList":    mail.ParseAddressList,
	"ParseDate":           mail.ParseDate,
	"ReadMessage":         mail.ReadMessage,
}
