package export

// Generated by 'goexports crypto/cipher'. Do not edit!

import "crypto/cipher"

// CryptoCipher contains exported symbols from crypto/cipher
var CryptoCipher = &map[string]interface{}{
	"AEAD":                new(cipher.AEAD),
	"Block":               new(cipher.Block),
	"BlockMode":           new(cipher.BlockMode),
	"NewCBCDecrypter":     cipher.NewCBCDecrypter,
	"NewCBCEncrypter":     cipher.NewCBCEncrypter,
	"NewCFBDecrypter":     cipher.NewCFBDecrypter,
	"NewCFBEncrypter":     cipher.NewCFBEncrypter,
	"NewCTR":              cipher.NewCTR,
	"NewGCM":              cipher.NewGCM,
	"NewGCMWithNonceSize": cipher.NewGCMWithNonceSize,
	"NewOFB":              cipher.NewOFB,
	"Stream":              new(cipher.Stream),
	"StreamReader":        new(cipher.StreamReader),
	"StreamWriter":        new(cipher.StreamWriter),
}
