package export

// Generated by 'go run gen.go net/smtp'. Do not edit!

import "net/smtp"

var sym_smtp = &map[string]interface{}{
	"Auth":        new(smtp.Auth),
	"CRAMMD5Auth": smtp.CRAMMD5Auth,
	"Client":      new(smtp.Client),
	"Dial":        smtp.Dial,
	"NewClient":   smtp.NewClient,
	"PlainAuth":   smtp.PlainAuth,
	"SendMail":    smtp.SendMail,
	"ServerInfo":  new(smtp.ServerInfo),
}
