package export

// Generated by 'go run gen.go crypto/elliptic'. Do not edit!

import "crypto/elliptic"

var sym_elliptic = &map[string]interface{}{
	"Curve":       new(elliptic.Curve),
	"CurveParams": new(elliptic.CurveParams),
	"GenerateKey": elliptic.GenerateKey,
	"Marshal":     elliptic.Marshal,
	"P224":        elliptic.P224,
	"P256":        elliptic.P256,
	"P384":        elliptic.P384,
	"P521":        elliptic.P521,
	"Unmarshal":   elliptic.Unmarshal,
}
