package export

// Generated by 'goexports crypto/subtle'. Do not edit!

import "crypto/subtle"

// CryptoSubtle contains exported symbols from crypto/subtle
var CryptoSubtle = &map[string]interface{}{
	"ConstantTimeByteEq":   subtle.ConstantTimeByteEq,
	"ConstantTimeCompare":  subtle.ConstantTimeCompare,
	"ConstantTimeCopy":     subtle.ConstantTimeCopy,
	"ConstantTimeEq":       subtle.ConstantTimeEq,
	"ConstantTimeLessOrEq": subtle.ConstantTimeLessOrEq,
	"ConstantTimeSelect":   subtle.ConstantTimeSelect,
}
