package export

// Generated by 'go run gen.go io/ioutil'. Do not edit!

import "io/ioutil"

var sym_ioutil = &map[string]interface{}{
	"Discard":   ioutil.Discard,
	"NopCloser": ioutil.NopCloser,
	"ReadAll":   ioutil.ReadAll,
	"ReadDir":   ioutil.ReadDir,
	"ReadFile":  ioutil.ReadFile,
	"TempDir":   ioutil.TempDir,
	"TempFile":  ioutil.TempFile,
	"WriteFile": ioutil.WriteFile,
}
