package export

// Generated by 'goexports go/printer'. Do not edit!

import "go/printer"

// GoPrinter contains exported symbols from go/printer
var GoPrinter = &map[string]interface{}{
	"CommentedNode": new(printer.CommentedNode),
	"Config":        new(printer.Config),
	"Fprint":        printer.Fprint,
	"Mode":          new(printer.Mode),
	"RawFormat":     printer.RawFormat,
	"SourcePos":     printer.SourcePos,
	"TabIndent":     printer.TabIndent,
	"UseSpaces":     printer.UseSpaces,
}
