package export

// Generated by 'go run gen.go bufio'. Do not edit!

import "bufio"

var sym_bufio = &map[string]interface{}{
	"ErrAdvanceTooFar":     bufio.ErrAdvanceTooFar,
	"ErrBufferFull":        bufio.ErrBufferFull,
	"ErrFinalToken":        bufio.ErrFinalToken,
	"ErrInvalidUnreadByte": bufio.ErrInvalidUnreadByte,
	"ErrInvalidUnreadRune": bufio.ErrInvalidUnreadRune,
	"ErrNegativeAdvance":   bufio.ErrNegativeAdvance,
	"ErrNegativeCount":     bufio.ErrNegativeCount,
	"ErrTooLong":           bufio.ErrTooLong,
	"MaxScanTokenSize":     bufio.MaxScanTokenSize,
	"NewReadWriter":        bufio.NewReadWriter,
	"NewReader":            bufio.NewReader,
	"NewReaderSize":        bufio.NewReaderSize,
	"NewScanner":           bufio.NewScanner,
	"NewWriter":            bufio.NewWriter,
	"NewWriterSize":        bufio.NewWriterSize,
	"ReadWriter":           new(bufio.ReadWriter),
	"Reader":               new(bufio.Reader),
	"ScanBytes":            bufio.ScanBytes,
	"ScanLines":            bufio.ScanLines,
	"ScanRunes":            bufio.ScanRunes,
	"ScanWords":            bufio.ScanWords,
	"Scanner":              new(bufio.Scanner),
	"SplitFunc":            new(bufio.SplitFunc),
	"Writer":               new(bufio.Writer),
}
