package export

// Generated by 'goexports net/http/cgi'. Do not edit!

import "net/http/cgi"

// HTTPCgi contains exported symbols from net/http/cgi
var HTTPCgi = &map[string]interface{}{
	"Handler":        new(cgi.Handler),
	"Request":        cgi.Request,
	"RequestFromMap": cgi.RequestFromMap,
	"Serve":          cgi.Serve,
}
