package export

// Generated by 'go run gen.go os/user'. Do not edit!

import "os/user"

var sym_user = &map[string]interface{}{
	"Current":             user.Current,
	"Group":               new(user.Group),
	"Lookup":              user.Lookup,
	"LookupGroup":         user.LookupGroup,
	"LookupGroupId":       user.LookupGroupId,
	"LookupId":            user.LookupId,
	"UnknownGroupError":   new(user.UnknownGroupError),
	"UnknownGroupIdError": new(user.UnknownGroupIdError),
	"UnknownUserError":    new(user.UnknownUserError),
	"UnknownUserIdError":  new(user.UnknownUserIdError),
	"User":                new(user.User),
}
