package export

// Generated by 'goexports crypto/ecdsa'. Do not edit!

import "crypto/ecdsa"

// CryptoEcdsa contains exported symbols from crypto/ecdsa
var CryptoEcdsa = &map[string]interface{}{
	"GenerateKey": ecdsa.GenerateKey,
	"PrivateKey":  new(ecdsa.PrivateKey),
	"PublicKey":   new(ecdsa.PublicKey),
	"Sign":        ecdsa.Sign,
	"Verify":      ecdsa.Verify,
}
