package export

// Generated by 'go run gen.go hash/crc64'. Do not edit!

import "hash/crc64"

var sym_crc64 = &map[string]interface{}{
	"Checksum":  crc64.Checksum,
	"ECMA":      uint(crc64.ECMA),
	"ISO":       uint(crc64.ISO),
	"MakeTable": crc64.MakeTable,
	"New":       crc64.New,
	"Size":      crc64.Size,
	"Table":     new(crc64.Table),
	"Update":    crc64.Update,
}
