package export

// Generated by 'go run gen.go mime/quotedprintable'. Do not edit!

import "mime/quotedprintable"

var sym_quotedprintable = &map[string]interface{}{
	"NewReader": quotedprintable.NewReader,
	"NewWriter": quotedprintable.NewWriter,
	"Reader":    new(quotedprintable.Reader),
	"Writer":    new(quotedprintable.Writer),
}
