package export

// Generated by 'goexports go/build'. Do not edit!

import "go/build"

// GoBuild contains exported symbols from go/build
var GoBuild = &map[string]interface{}{
	"AllowBinary":          build.AllowBinary,
	"ArchChar":             build.ArchChar,
	"Context":              new(build.Context),
	"Default":              build.Default,
	"FindOnly":             build.FindOnly,
	"IgnoreVendor":         build.IgnoreVendor,
	"Import":               build.Import,
	"ImportComment":        build.ImportComment,
	"ImportDir":            build.ImportDir,
	"ImportMode":           new(build.ImportMode),
	"IsLocalImport":        build.IsLocalImport,
	"MultiplePackageError": new(build.MultiplePackageError),
	"NoGoError":            new(build.NoGoError),
	"Package":              new(build.Package),
	"ToolDir":              build.ToolDir,
}
