package export

// Generated by 'go run gen.go image/color'. Do not edit!

import "image/color"

var sym_color = &map[string]interface{}{
	"Alpha":        new(color.Alpha),
	"Alpha16":      new(color.Alpha16),
	"Alpha16Model": color.Alpha16Model,
	"AlphaModel":   color.AlphaModel,
	"Black":        color.Black,
	"CMYK":         new(color.CMYK),
	"CMYKModel":    color.CMYKModel,
	"CMYKToRGB":    color.CMYKToRGB,
	"Color":        new(color.Color),
	"Gray":         new(color.Gray),
	"Gray16":       new(color.Gray16),
	"Gray16Model":  color.Gray16Model,
	"GrayModel":    color.GrayModel,
	"Model":        new(color.Model),
	"ModelFunc":    color.ModelFunc,
	"NRGBA":        new(color.NRGBA),
	"NRGBA64":      new(color.NRGBA64),
	"NRGBA64Model": color.NRGBA64Model,
	"NRGBAModel":   color.NRGBAModel,
	"NYCbCrA":      new(color.NYCbCrA),
	"NYCbCrAModel": color.NYCbCrAModel,
	"Opaque":       color.Opaque,
	"Palette":      new(color.Palette),
	"RGBA":         new(color.RGBA),
	"RGBA64":       new(color.RGBA64),
	"RGBA64Model":  color.RGBA64Model,
	"RGBAModel":    color.RGBAModel,
	"RGBToCMYK":    color.RGBToCMYK,
	"RGBToYCbCr":   color.RGBToYCbCr,
	"Transparent":  color.Transparent,
	"White":        color.White,
	"YCbCr":        new(color.YCbCr),
	"YCbCrModel":   color.YCbCrModel,
	"YCbCrToRGB":   color.YCbCrToRGB,
}
