package export

// Generated by 'go run gen.go compress/bzip2'. Do not edit!

import "compress/bzip2"

var sym_bzip2 = &map[string]interface{}{
	"NewReader":       bzip2.NewReader,
	"StructuralError": new(bzip2.StructuralError),
}
