package export

// Generated by 'goexports index/suffixarray'. Do not edit!

import "index/suffixarray"

// IndexSuffixarray contains exported symbols from index/suffixarray
var IndexSuffixarray = &map[string]interface{}{
	"Index": new(suffixarray.Index),
	"New":   suffixarray.New,
}
