package export

// Generated by 'go run gen.go encoding/base32'. Do not edit!

import "encoding/base32"

var sym_base32 = &map[string]interface{}{
	"CorruptInputError": new(base32.CorruptInputError),
	"Encoding":          new(base32.Encoding),
	"HexEncoding":       base32.HexEncoding,
	"NewDecoder":        base32.NewDecoder,
	"NewEncoder":        base32.NewEncoder,
	"NewEncoding":       base32.NewEncoding,
	"NoPadding":         base32.NoPadding,
	"StdEncoding":       base32.StdEncoding,
	"StdPadding":        base32.StdPadding,
}
