package export

// Generated by 'goexports hash/crc32'. Do not edit!

import "hash/crc32"

// HashCrc32 contains exported symbols from hash/crc32
var HashCrc32 = &map[string]interface{}{
	"Castagnoli":   crc32.Castagnoli,
	"Checksum":     crc32.Checksum,
	"ChecksumIEEE": crc32.ChecksumIEEE,
	"IEEE":         crc32.IEEE,
	"IEEETable":    crc32.IEEETable,
	"Koopman":      crc32.Koopman,
	"MakeTable":    crc32.MakeTable,
	"New":          crc32.New,
	"NewIEEE":      crc32.NewIEEE,
	"Size":         crc32.Size,
	"Table":        new(crc32.Table),
	"Update":       crc32.Update,
}
