package export

// Generated by 'goexports mime'. Do not edit!

import "mime"

// Mime contains exported symbols from mime
var Mime = &map[string]interface{}{
	"AddExtensionType":         mime.AddExtensionType,
	"BEncoding":                mime.BEncoding,
	"ErrInvalidMediaParameter": mime.ErrInvalidMediaParameter,
	"ExtensionsByType":         mime.ExtensionsByType,
	"FormatMediaType":          mime.FormatMediaType,
	"ParseMediaType":           mime.ParseMediaType,
	"QEncoding":                mime.QEncoding,
	"TypeByExtension":          mime.TypeByExtension,
	"WordDecoder":              new(mime.WordDecoder),
	"WordEncoder":              new(mime.WordEncoder),
}
