package export

// Generated by 'goexports net/textproto'. Do not edit!

import "net/textproto"

// NetTextproto contains exported symbols from net/textproto
var NetTextproto = &map[string]interface{}{
	"CanonicalMIMEHeaderKey": textproto.CanonicalMIMEHeaderKey,
	"Conn":          new(textproto.Conn),
	"Dial":          textproto.Dial,
	"Error":         new(textproto.Error),
	"MIMEHeader":    new(textproto.MIMEHeader),
	"NewConn":       textproto.NewConn,
	"NewReader":     textproto.NewReader,
	"NewWriter":     textproto.NewWriter,
	"Pipeline":      new(textproto.Pipeline),
	"ProtocolError": new(textproto.ProtocolError),
	"Reader":        new(textproto.Reader),
	"TrimBytes":     textproto.TrimBytes,
	"TrimString":    textproto.TrimString,
	"Writer":        new(textproto.Writer),
}
