package export

// Generated by 'goexports expvar'. Do not edit!

import "expvar"

// Expvar contains exported symbols from expvar
var Expvar = &map[string]interface{}{
	"Do":        expvar.Do,
	"Float":     new(expvar.Float),
	"Func":      new(expvar.Func),
	"Get":       expvar.Get,
	"Handler":   expvar.Handler,
	"Int":       new(expvar.Int),
	"KeyValue":  new(expvar.KeyValue),
	"Map":       new(expvar.Map),
	"NewFloat":  expvar.NewFloat,
	"NewInt":    expvar.NewInt,
	"NewMap":    expvar.NewMap,
	"NewString": expvar.NewString,
	"Publish":   expvar.Publish,
	"String":    new(expvar.String),
	"Var":       new(expvar.Var),
}
