package export

// Generated by 'go run gen.go net/http/cgi'. Do not edit!

import "net/http/cgi"

var sym_cgi = &map[string]interface{}{
	"Handler":        new(cgi.Handler),
	"Request":        cgi.Request,
	"RequestFromMap": cgi.RequestFromMap,
	"Serve":          cgi.Serve,
}
