package export

// Generated by 'goexports os/signal'. Do not edit!

import "os/signal"

// OsSignal contains exported symbols from os/signal
var OsSignal = &map[string]interface{}{
	"Ignore": signal.Ignore,
	"Notify": signal.Notify,
	"Reset":  signal.Reset,
	"Stop":   signal.Stop,
}
