package export

// Generated by 'go run gen.go unicode/utf16'. Do not edit!

import "unicode/utf16"

var sym_utf16 = &map[string]interface{}{
	"Decode":      utf16.Decode,
	"DecodeRune":  utf16.DecodeRune,
	"Encode":      utf16.Encode,
	"EncodeRune":  utf16.EncodeRune,
	"IsSurrogate": utf16.IsSurrogate,
}
