package export

// Generated by 'go run gen.go container/heap'. Do not edit!

import "container/heap"

var sym_heap = &map[string]interface{}{
	"Fix":       heap.Fix,
	"Init":      heap.Init,
	"Interface": new(heap.Interface),
	"Pop":       heap.Pop,
	"Push":      heap.Push,
	"Remove":    heap.Remove,
}
