package export

// Generated by 'go run gen.go html'. Do not edit!

import "html"

var sym_html = &map[string]interface{}{
	"EscapeString":   html.EscapeString,
	"UnescapeString": html.UnescapeString,
}
