package export

// Generated by 'goexports encoding/gob'. Do not edit!

import "encoding/gob"

// EncodingGob contains exported symbols from encoding/gob
var EncodingGob = &map[string]interface{}{
	"CommonType":   new(gob.CommonType),
	"Decoder":      new(gob.Decoder),
	"Encoder":      new(gob.Encoder),
	"GobDecoder":   new(gob.GobDecoder),
	"GobEncoder":   new(gob.GobEncoder),
	"NewDecoder":   gob.NewDecoder,
	"NewEncoder":   gob.NewEncoder,
	"Register":     gob.Register,
	"RegisterName": gob.RegisterName,
}
