package export

// Generated by 'go run gen.go unicode/utf8'. Do not edit!

import "unicode/utf8"

var sym_utf8 = &map[string]interface{}{
	"DecodeLastRune":         utf8.DecodeLastRune,
	"DecodeLastRuneInString": utf8.DecodeLastRuneInString,
	"DecodeRune":             utf8.DecodeRune,
	"DecodeRuneInString":     utf8.DecodeRuneInString,
	"EncodeRune":             utf8.EncodeRune,
	"FullRune":               utf8.FullRune,
	"FullRuneInString":       utf8.FullRuneInString,
	"MaxRune":                utf8.MaxRune,
	"RuneCount":              utf8.RuneCount,
	"RuneCountInString":      utf8.RuneCountInString,
	"RuneError":              utf8.RuneError,
	"RuneLen":                utf8.RuneLen,
	"RuneSelf":               utf8.RuneSelf,
	"RuneStart":              utf8.RuneStart,
	"UTFMax":                 utf8.UTFMax,
	"Valid":                  utf8.Valid,
	"ValidRune":              utf8.ValidRune,
	"ValidString":            utf8.ValidString,
}
