package export

// Generated by 'go run gen.go image/gif'. Do not edit!

import "image/gif"

var sym_gif = &map[string]interface{}{
	"Decode":             gif.Decode,
	"DecodeAll":          gif.DecodeAll,
	"DecodeConfig":       gif.DecodeConfig,
	"DisposalBackground": gif.DisposalBackground,
	"DisposalNone":       gif.DisposalNone,
	"DisposalPrevious":   gif.DisposalPrevious,
	"Encode":             gif.Encode,
	"EncodeAll":          gif.EncodeAll,
	"GIF":                new(gif.GIF),
	"Options":            new(gif.Options),
}
