package export

// Generated by 'goexports compress/gzip'. Do not edit!

import "compress/gzip"

// CompressGzip contains exported symbols from compress/gzip
var CompressGzip = &map[string]interface{}{
	"BestCompression":    gzip.BestCompression,
	"BestSpeed":          gzip.BestSpeed,
	"DefaultCompression": gzip.DefaultCompression,
	"ErrChecksum":        gzip.ErrChecksum,
	"ErrHeader":          gzip.ErrHeader,
	"Header":             new(gzip.Header),
	"HuffmanOnly":        gzip.HuffmanOnly,
	"NewReader":          gzip.NewReader,
	"NewWriter":          gzip.NewWriter,
	"NewWriterLevel":     gzip.NewWriterLevel,
	"NoCompression":      gzip.NoCompression,
	"Reader":             new(gzip.Reader),
	"Writer":             new(gzip.Writer),
}
