#!/bin/sh

echo 'package interp'
echo
echo '// Do not edit! File generated by ../test/gen_example.sh'
echo
echo 'import ('
echo '"fmt"'
echo '"math"'
echo ')'
for file in *.gi
do
	awk '
	$0 == "// Output:" { done = 1 }
	{ if (done) out = out "\n" $0; else src = src "\n" $0 }
	END {
		print "func Example_'${file%.*}'() {"
		print "src := `" src "`"
		print "i := NewInterpreter(InterpOpt{})"
		print "i.AddImport(\"fmt\", \"Println\", fmt.Println)"
		print "i.AddImport(\"math\", \"Pi\", math.Pi)"
		print "i.AddImport(\"math\", \"Cos\", math.Cos)"
		print "i.Eval(src)"
		print out
		print "}"
	}
	' $file

	echo
done
