project_name: yaegi

builds:
  - id: yaegi
    binary: yaegi
    main: ./cmd/yaegi/

    goos:
      - darwin
      - linux
#      - windows
      - freebsd
      - openbsd
      - solaris
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
      - 6
      - 5

    ignore:
      - goos: darwin
        goarch: 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: archive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

brews:
  - repository:
      owner: traefik
      name: homebrew-tap
    commit_author:
      name: traefiker
      email: 30906710+traefiker@users.noreply.github.com
    folder: Formula
    homepage: https://github.com/traefik/yaegi
    description: |
      Yaegi is Another Elegant Go Interpreter.
      It powers executable Go scripts and plugins, in embedded interpreters
      or interactive shells, on top of the Go runtime.
    test: |
      system "#{bin}/yaegi version"
