// +build go1.11,!go1.12

package unsafe

// Code generated by 'goexports unsafe'. DO NOT EDIT.

import (
	"reflect"
	"unsafe"
)

func init() {
	Symbols["unsafe"] = map[string]reflect.Value{
		// function, constant and variable definitions

		// type definitions
		"Pointer": reflect.ValueOf((*unsafe.Pointer)(nil)),

		// interface wrapper definitions

	}
}
