// Code generated by 'yaegi extract unsafe'. DO NOT EDIT.

// +build go1.15,!go1.16

package unsafe

import (
	"reflect"
	"unsafe"
)

func init() {
	Symbols["unsafe"] = map[string]reflect.Value{
		// default package name identifier
		".name": reflect.ValueOf("unsafe"),

		// type definitions
		"Pointer": reflect.ValueOf((*unsafe.Pointer)(nil)),
	}
}
