// Code generated by 'goexports unsafe'. DO NOT EDIT.

// +build go1.11,!go1.12

package unsafe

import (
	"reflect"
	"unsafe"
)

func init() {
	Symbols["unsafe"] = map[string]reflect.Value{
		// type definitions
		"Pointer": reflect.ValueOf((*unsafe.Pointer)(nil)),
	}
}
