package stdlib

// Code generated by 'goexports compress/bzip2'. DO NOT EDIT.

import (
	"compress/bzip2"
	"reflect"
)

func init() {
	Value["compress/bzip2"] = map[string]reflect.Value{
		"NewReader": reflect.ValueOf(bzip2.NewReader),
	}
	Type["compress/bzip2"] = map[string]reflect.Type{
		"StructuralError": reflect.TypeOf((*bzip2.StructuralError)(nil)).Elem(),
	}
}
