package stdlib

// Generated by 'goexports container/ring'. Do not edit!

import (
	"container/ring"
	"reflect"
)

func init() {
	Value["container/ring"] = map[string]reflect.Value{
		"New": reflect.ValueOf(ring.New),
	}
	Type["container/ring"] = map[string]reflect.Type{
		"Ring": reflect.TypeOf((*ring.Ring)(nil)).Elem(),
	}
}
