package stdlib

// Generated by 'goexports crypto/sha1'. Do not edit!

import (
	"crypto/sha1"
	"reflect"
)

func init() {
	Value["crypto/sha1"] = map[string]reflect.Value{
		"BlockSize": reflect.ValueOf(sha1.BlockSize),
		"New":       reflect.ValueOf(sha1.New),
		"Size":      reflect.ValueOf(sha1.Size),
		"Sum":       reflect.ValueOf(sha1.Sum),
	}
	Type["crypto/sha1"] = map[string]reflect.Type{}
}
