package stdlib

// Generated by 'goexports crypto/hmac'. Do not edit!

import (
	"crypto/hmac"
	"reflect"
)

func init() {
	Value["crypto/hmac"] = map[string]reflect.Value{
		"Equal": reflect.ValueOf(hmac.Equal),
		"New":   reflect.ValueOf(hmac.New),
	}
	Type["crypto/hmac"] = map[string]reflect.Type{}
}
