package stdlib

// Generated by 'goexports encoding/csv'. Do not edit!

import (
	"encoding/csv"
	"reflect"
)

func init() {
	Value["encoding/csv"] = map[string]reflect.Value{
		"ErrBareQuote":     reflect.ValueOf(csv.ErrBareQuote),
		"ErrFieldCount":    reflect.ValueOf(csv.ErrFieldCount),
		"ErrQuote":         reflect.ValueOf(csv.ErrQuote),
		"ErrTrailingComma": reflect.ValueOf(csv.ErrTrailingComma),
		"NewReader":        reflect.ValueOf(csv.NewReader),
		"NewWriter":        reflect.ValueOf(csv.NewWriter),
	}
	Type["encoding/csv"] = map[string]reflect.Type{
		"ParseError": reflect.TypeOf((*csv.ParseError)(nil)).Elem(),
		"Reader":     reflect.TypeOf((*csv.Reader)(nil)).Elem(),
		"Writer":     reflect.TypeOf((*csv.Writer)(nil)).Elem(),
	}
}
