package stdlib

// Code generated by 'goexports encoding'. DO NOT EDIT.

import (
	"encoding"
	"reflect"
)

func init() {
	Value["encoding"] = map[string]reflect.Value{}
	Type["encoding"] = map[string]reflect.Type{
		"BinaryMarshaler":   reflect.TypeOf((*encoding.BinaryMarshaler)(nil)).Elem(),
		"BinaryUnmarshaler": reflect.TypeOf((*encoding.BinaryUnmarshaler)(nil)).Elem(),
		"TextMarshaler":     reflect.TypeOf((*encoding.TextMarshaler)(nil)).Elem(),
		"TextUnmarshaler":   reflect.TypeOf((*encoding.TextUnmarshaler)(nil)).Elem(),
	}
}
