package stdlib

// Code generated by 'goexports errors'. DO NOT EDIT.

import (
	"errors"
	"reflect"
)

func init() {
	Value["errors"] = map[string]reflect.Value{
		"New": reflect.ValueOf(errors.New),
	}
	Type["errors"] = map[string]reflect.Type{}
}
