// Code generated by 'goexports crypto/md5'. DO NOT EDIT.

// +build go1.11,!go1.12

package stdlib

import (
	"crypto/md5"
	"reflect"
)

func init() {
	Symbols["crypto/md5"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BlockSize": reflect.ValueOf(md5.BlockSize),
		"New":       reflect.ValueOf(md5.New),
		"Size":      reflect.ValueOf(md5.Size),
		"Sum":       reflect.ValueOf(md5.Sum),
	}
}
