// Code generated by 'goexports compress/bzip2'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlib

import (
	"compress/bzip2"
	"reflect"
)

func init() {
	Symbols["compress/bzip2"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewReader": reflect.ValueOf(bzip2.NewReader),

		// type definitions
		"StructuralError": reflect.ValueOf((*bzip2.StructuralError)(nil)),
	}
}
