// Code generated by 'goexports crypto/sha1'. DO NOT EDIT.

// +build go1.13,!go1.14

package stdlib

import (
	"crypto/sha1"
	"reflect"
)

func init() {
	Symbols["crypto/sha1"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BlockSize": reflect.ValueOf(sha1.BlockSize),
		"New":       reflect.ValueOf(sha1.New),
		"Size":      reflect.ValueOf(sha1.Size),
		"Sum":       reflect.ValueOf(sha1.Sum),
	}
}
