// Code generated by 'goexports hash/adler32'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlib

import (
	"hash/adler32"
	"reflect"
)

func init() {
	Symbols["hash/adler32"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Checksum": reflect.ValueOf(adler32.Checksum),
		"New":      reflect.ValueOf(adler32.New),
		"Size":     reflect.ValueOf(adler32.Size),
	}
}
