// Code generated by 'goexports html'. DO NOT EDIT.

// +build go1.12,!go1.13

package stdlib

import (
	"html"
	"reflect"
)

func init() {
	Symbols["html"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"EscapeString":   reflect.ValueOf(html.EscapeString),
		"UnescapeString": reflect.ValueOf(html.UnescapeString),
	}
}
