// +build go1.12, !go1.13

package stdlib

// Code generated by 'goexports container/heap'. DO NOT EDIT.

import (
	"container/heap"
	"reflect"
)

func init() {
	Value["container/heap"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Fix":    reflect.ValueOf(heap.Fix),
		"Init":   reflect.ValueOf(heap.Init),
		"Pop":    reflect.ValueOf(heap.Pop),
		"Push":   reflect.ValueOf(heap.Push),
		"Remove": reflect.ValueOf(heap.Remove),

		// type definitions
		"Interface": reflect.ValueOf((*heap.Interface)(nil)),
	}
}
