// +build go1.11,!go1.12

package stdlib

// Code generated by 'goexports go/format'. DO NOT EDIT.

import (
	"go/format"
	"reflect"
)

func init() {
	Value["go/format"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Node":   reflect.ValueOf(format.Node),
		"Source": reflect.ValueOf(format.Source),

		// type definitions

	}
}
