// +build go1.11,!go1.12

package stdlib

// Code generated by 'goexports encoding/pem'. DO NOT EDIT.

import (
	"encoding/pem"
	"reflect"
)

func init() {
	Value["encoding/pem"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Decode":         reflect.ValueOf(pem.Decode),
		"Encode":         reflect.ValueOf(pem.Encode),
		"EncodeToMemory": reflect.ValueOf(pem.EncodeToMemory),

		// type definitions
		"Block": reflect.ValueOf((*pem.Block)(nil)),
	}
	Wrapper["encoding/pem"] = map[string]reflect.Type{}
}
