package stdlib

// Code generated by 'goexports html'. DO NOT EDIT.

import (
	"html"
	"reflect"
)

func init() {
	Value["html"] = map[string]reflect.Value{
		"EscapeString":   reflect.ValueOf(html.EscapeString),
		"UnescapeString": reflect.ValueOf(html.UnescapeString),
	}
	Type["html"] = map[string]reflect.Type{}
}
