package stdlib

// Generated by 'goexports image/jpeg'. Do not edit!

import (
	"image/jpeg"
	"reflect"
)

func init() {
	Value["image/jpeg"] = map[string]reflect.Value{
		"Decode":         reflect.ValueOf(jpeg.Decode),
		"DecodeConfig":   reflect.ValueOf(jpeg.DecodeConfig),
		"DefaultQuality": reflect.ValueOf(jpeg.DefaultQuality),
		"Encode":         reflect.ValueOf(jpeg.Encode),
	}
	Type["image/jpeg"] = map[string]reflect.Type{
		"FormatError":      reflect.TypeOf((*jpeg.FormatError)(nil)).Elem(),
		"Options":          reflect.TypeOf((*jpeg.Options)(nil)).Elem(),
		"Reader":           reflect.TypeOf((*jpeg.Reader)(nil)).Elem(),
		"UnsupportedError": reflect.TypeOf((*jpeg.UnsupportedError)(nil)).Elem(),
	}
}
