package stdlib

// Code generated by 'goexports image/color/palette'. DO NOT EDIT.

import (
	"image/color/palette"
	"reflect"
)

func init() {
	Value["image/color/palette"] = map[string]reflect.Value{
		"Plan9":   reflect.ValueOf(palette.Plan9),
		"WebSafe": reflect.ValueOf(palette.WebSafe),
	}

	Type["image/color/palette"] = map[string]reflect.Type{}
}
