package stdlib

// Generated by 'goexports mime/multipart'. Do not edit!

import (
	"mime/multipart"
	"reflect"
)

func init() {
	Value["mime/multipart"] = map[string]reflect.Value{
		"ErrMessageTooLarge": reflect.ValueOf(multipart.ErrMessageTooLarge),
		"NewReader":          reflect.ValueOf(multipart.NewReader),
		"NewWriter":          reflect.ValueOf(multipart.NewWriter),
	}
	Type["mime/multipart"] = map[string]reflect.Type{
		"File":       reflect.TypeOf((*multipart.File)(nil)).Elem(),
		"FileHeader": reflect.TypeOf((*multipart.FileHeader)(nil)).Elem(),
		"Form":       reflect.TypeOf((*multipart.Form)(nil)).Elem(),
		"Part":       reflect.TypeOf((*multipart.Part)(nil)).Elem(),
		"Reader":     reflect.TypeOf((*multipart.Reader)(nil)).Elem(),
		"Writer":     reflect.TypeOf((*multipart.Writer)(nil)).Elem(),
	}
}
