package stdlib

// Code generated by 'goexports net/rpc/jsonrpc'. DO NOT EDIT.

import (
	"net/rpc/jsonrpc"
	"reflect"
)

func init() {
	Value["net/rpc/jsonrpc"] = map[string]reflect.Value{
		"Dial":           reflect.ValueOf(jsonrpc.Dial),
		"NewClient":      reflect.ValueOf(jsonrpc.NewClient),
		"NewClientCodec": reflect.ValueOf(jsonrpc.NewClientCodec),
		"NewServerCodec": reflect.ValueOf(jsonrpc.NewServerCodec),
		"ServeConn":      reflect.ValueOf(jsonrpc.ServeConn),
	}
	Type["net/rpc/jsonrpc"] = map[string]reflect.Type{}
}
