package stdlib

// Code generated by 'goexports os/exec'. DO NOT EDIT.

import (
	"os/exec"
	"reflect"
)

func init() {
	Value["os/exec"] = map[string]reflect.Value{
		"Command":        reflect.ValueOf(exec.Command),
		"CommandContext": reflect.ValueOf(exec.CommandContext),
		"ErrNotFound":    reflect.ValueOf(&exec.ErrNotFound).Elem(),
		"LookPath":       reflect.ValueOf(exec.LookPath),
	}

	Type["os/exec"] = map[string]reflect.Type{
		"Cmd":       reflect.TypeOf((*exec.Cmd)(nil)).Elem(),
		"Error":     reflect.TypeOf((*exec.Error)(nil)).Elem(),
		"ExitError": reflect.TypeOf((*exec.ExitError)(nil)).Elem(),
	}
}
